name: Update Notion

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
         node-version: 16
         cache: 'pnpm'
      - run: pnpm install
      - name: Run script
        run: pnpm start
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
