name: Update Notion

on:
  push:
    branches:
      - main
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 16
         cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install
      - name: Run script
        run: pnpm start
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
